"""The periodic table as an array, indexed by atomic number.

Deliberately free of PyTorch. This is the load-bearing piece of Phase 5 -- if the
table is misaligned by one row, every atom in the dataset gets the properties of
its neighbour in the periodic table and the result would look like a plausible
but disappointing experiment rather than a bug. Keeping it importable without
torch means it can be tested on any machine, which is the same reason
``cgcnn_reference.py`` exists.

The properties themselves come from the committed reference table generated by
``scripts/make_element_table.py``, so a pymatgen upgrade cannot silently change
what "electronegativity" means halfway through a project.
"""

from __future__ import annotations

import numpy as np

from .descriptors import element_table, property_matrix


def element_feature_table(max_z: int = 100
                          ) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Standardised element properties, row Z holding element Z.

    Returns
    -------
    table : (max_z + 1, n_props) float32
        Row 0, and any element absent from the reference table, is all zeros --
        which after standardising is *the average element*. A neutral default is
        the right behaviour for something unknown; a random vector is not, and a
        random vector is precisely what the learned embedding gives.
    known : (max_z + 1,) bool
        Which rows are real, so a dataset containing an element outside the
        table cannot pass silently.
    names : list[str]

    Standardised per column across the elements themselves. That uses no labels
    and no training data, so it is a fixed property of the periodic table rather
    than something fitted -- which is why it is here and not in the training loop
    beside the target normaliser.

    Without standardising, the columns span five orders of magnitude (melting
    point ~3700 K against electronegativity ~0.7-4.0) and the first weight
    updates of the projection layer would be almost entirely about melting point.
    """
    elements, _ = element_table()
    index, mat, props = property_matrix()          # symbol -> row, (n_el, n_props)
    props = list(props)

    table = np.zeros((max_z + 1, mat.shape[1]), dtype=np.float64)
    known = np.zeros(max_z + 1, dtype=bool)

    for symbol, row in index.items():
        z = int(elements[symbol]["Z"])
        if 0 <= z <= max_z:
            table[z] = mat[row]
            known[z] = True

    mu = table[known].mean(axis=0)
    sigma = table[known].std(axis=0)
    sigma[sigma == 0] = 1.0                        # constant column -> zeros

    table[known] = (table[known] - mu) / sigma
    table[~known] = 0.0

    return table.astype(np.float32), known, props
